package scala.xml

object Events {

  inline def get(key: String): String = {
    if key.startsWith("on") then key.drop(2)
    else key
  }
//  val events =
//    Map(
//    "onclick"              -> "click",
//    "ondblclick"           -> "dblclick",
//    "onmousedown"          -> "mousedown",
//    "onmousemove"          -> "mousemove",
//    "onmouseout"           -> "mouseout",
//    "onmouseover"          -> "mouseover",
//    "onmouseleave"         -> "mouseleave",
//    "onmouseenter"         -> "mouseenter",
//    "onmouseup"            -> "mouseup",
//    "onwheel"              -> "wheel",
//    "oncontextmenu"        -> "contextmenu",
//    "ondrag"               -> "drag",
//    "ondragend"            -> "dragend",
//    "ondragenter"          -> "dragenter",
//    "ondragleave"          -> "dragleave",
//    "ondragover"           -> "dragover",
//    "ondragstart"          -> "dragstart",
//    "ondrop"               -> "drop",
//    "onpointerover"        -> "pointerover",
//    "onpointerenter"       -> "pointerenter",
//    "onpointerdown"        -> "pointerdown",
//    "onpointermove"        -> "pointermove",
//    "onpointerup"          -> "pointerup",
//    "onpointercancel"      -> "pointercancel",
//    "onpointerout"         -> "pointerout",
//    "onpointerleave"       -> "pointerleave",
//    "ongotpointercapture"  -> "gotpointercapture",
//    "onlostpointercapture" -> "lostpointercapture",
//    "ontouchstart"         -> "touchstart",
//    "ontouchmove"          -> "touchmove",
//    "ontouchcancel"        -> "touchcancel",
//    "ontouchend"           -> "touchend",
//    "onchange"             -> "change",
//    "onselect"             -> "select",
//    "onbeforeinput"        -> "beforeinput",
//    "oninput"              -> "input",
//    "onblur"               -> "blur",
//    "onfocus"              -> "focus",
//    "onsubmit"             -> "submit",
//    "onreset"              -> "reset",
//    "oninvalid"            -> "invalid",
//    "onsearch"             -> "search",
//    "onkeydown"            -> "keydown",
//    "onkeyup"              -> "keyup",
//    "onkeypress"           -> "keypress",
//    "oncopy"               -> "copy",
//    "oncut"                -> "cut",
//    "onpaste"              -> "paste",
//    "onabort"              -> "abort",
//    "oncanplay"            -> "canplay",
//    "oncanplaythrough"     -> "canplaythrough",
//    "oncuechange"          -> "cuechange",
//    "ondurationchange"     -> "durationchange",
//    "onemptied"            -> "emptied",
//    "onended"              -> "ended",
//    "onloadeddata"         -> "loadeddata",
//    "onloadedmetadata"     -> "loadedmetadata",
//    "onloadstart"          -> "loadstart",
//    "onpause"              -> "pause",
//    "onplay"               -> "play",
//    "onplaying"            -> "playing",
//    "onprogress"           -> "progress",
//    "onratechange"         -> "ratechange",
//    "onseeked"             -> "seeked",
//    "onseeking"            -> "seeking",
//    "onstalled"            -> "stalled",
//    "onsuspend"            -> "suspend",
//    "ontimeupdate"         -> "timeupdate",
//    "onvolumechange"       -> "volumechange",
//    "onwaiting"            -> "waiting",
//    "onanimationend"       -> "animationend",
//    "onanimationiteration" -> "animationiteration",
//    "onanimationstart"     -> "animationstart",
//    "ontransitionend"      -> "transitionend",
//    "onload"               -> "load",
//    "onresize"             -> "resize",
//    "onscroll"             -> "scroll",
//    "onselectstart"        -> "selectstart",
//    "onshow"               -> "show",
//    "ontoggle"             -> "toggle",
//    "onerror"              -> "error",
//  )
}
