//addSbtPlugin("com.github.sbt" % "sbt-dynver" % "5.0.1")
addSbtPlugin("org.scala-js"   % "sbt-scalajs"    % "1.17.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"  % "0.12.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.9.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"   % "3.12.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp"        % "2.1.2")
addSbtPlugin("com.github.sbt" % "sbt-git"        % "2.1.0")
