package scala.xml
package binders

object Events {
  def key(e: String): Option[String] = unapply(e)

  def unapply(e: String): Option[String] = {
    val inputKey = if e.startsWith("on") then e.drop(2) else e
    eventKey.find(key => key.equalsIgnoreCase(inputKey))
  }

  val eventKey = Set(
    "click",
    "dblclick",
    "mousedown",
    "mousemove",
    "mouseout",
    "mouseover",
    "mouseleave",
    "mouseenter",
    "mouseup",
    "wheel",
    "contextmenu",
    "drag",
    "dragend",
    "dragenter",
    "dragleave",
    "dragover",
    "dragstart",
    "drop",
    "pointerover",
    "pointerenter",
    "pointerdown",
    "pointermove",
    "pointerup",
    "pointercancel",
    "pointerout",
    "pointerleave",
    "gotpointercapture",
    "lostpointercapture",
    "touchstart",
    "touchmove",
    "touchcancel",
    "touchend",
    "change",
    "select",
    "beforeinput",
    "input",
    "blur",
    "focus",
    "submit",
    "reset",
    "invalid",
    "search",
    "keydown",
    "keyup",
    "keypress",
    "copy",
    "cut",
    "paste",
    "abort",
    "canplay",
    "canplaythrough",
    "cuechange",
    "durationchange",
    "emptied",
    "ended",
    "loadeddata",
    "loadedmetadata",
    "loadstart",
    "pause",
    "play",
    "playing",
    "progress",
    "ratechange",
    "seeked",
    "seeking",
    "stalled",
    "suspend",
    "timeupdate",
    "volumechange",
    "waiting",
    "animationend",
    "animationiteration",
    "animationstart",
    "transitionend",
    "load",
    "resize",
    "scroll",
    "selectstart",
    "show",
    "toggle",
    "error",
  )
}
